#pragma once

#define EDGE_DETECTION_WIDTH 1000
#define STORED_EDGES_WIDTH 500

#define EDGE_DETECTION_BLUR_SIZE 21
#define EDGE_DETECTION_BLUR_SIGMA_X 5
#define EDGE_DETECTION_BLUR_SIGMA_Y 5
#define EDGE_DETECTION_CANNY_THRESHOLD_1 69
#define EDGE_DETECTION_CANNY_THRESHOLD_2 69
#define EDGE_DETECTION_CANNY_JOIN_BY_X 11
#define EDGE_DETECTION_CANNY_JOIN_BY_Y 11
#define EDGE_DETECTION_BINARY_THRESHOLD 100

#define MATCH_OFFSET_SCALE_STEP 0.1
#define MATCH_OFFSET_X_STEP 1
#define MATCH_OFFSET_Y_STEP 10
#define MATCH_MIN_OFFSET_SCALE 0.4
#define MATCH_MAX_OFFSET 15
#define MATCH_WHITE_BIAS 0.75

#define CANVAS_WIDTH 300
#define CANVAS_HEIGHT 200

#define OUTPUT_WIDTH 1500
#define OUTPUT_HEIGHT 1000

enum ImageEdgeModes {
  ImageEdgeMode_Canny,
  ImageEdgeMode_Threshold,
  ImageEdgeMode_Manual
};
