#pragma once

#define EDGE_DETECTION_WIDTH 900
#define STORED_EDGES_WIDTH 300

#define EDGE_DETECTION_BLUR_SIZE 21
#define EDGE_DETECTION_BLUR_SIGMA_X 5
#define EDGE_DETECTION_BLUR_SIGMA_Y 5
#define EDGE_DETECTION_CANNY_THRESHOLD_1 69
#define EDGE_DETECTION_CANNY_THRESHOLD_2 69
#define EDGE_DETECTION_CANNY_JOIN_BY_X 11
#define EDGE_DETECTION_CANNY_JOIN_BY_Y 11
#define EDGE_DETECTION_BINARY_THRESHOLD 100

#define CANVAS_WIDTH 300
#define CANVAS_HEIGHT 200

#define OUTPUT_WIDTH 1500
#define OUTPUT_HEIGHT 1000

enum ImageEdgeModes {
  ImageEdgeMode_Canny,
  ImageEdgeMode_Threshold,
  ImageEdgeMode_Manual
};
